---
- hosts: nginxNode
  remote_user: ubuntu
  vars:
    ansible_python_interpreter: /usr/bin/python3
    container_name: "nginx"
    container_image: "nginx"
    working_dir: "/data/nginx"
    server_hostname: "{{ nginxNode }}"
    
  vars_files:
    - host_vars/nginx.yaml
    - host_vars/local_vars.yaml
    - host_vars/remote_vars.yaml
    - host_vars/docker.yaml
    - host_vars/couchdb.yaml

  gather_facts: true
  
  roles:
    - role: nginx-balancer