export const OVERVIEW_DATA_RECEIVED = "OVERVIEW_DATA_RECEIVED";
export const UPDATE_LOADING_STATUS = "UPDATE_LOADING_STATUS";
export const LGA_DATA_RECEIVED = "LGA_DATA_RECEIVED";
export const CLEAR_LGA_DATA = "CLEAR_LGA_DATA";
