---
# Common vars
availability_zone: melbourne-qh2-uom

# Instance_flavor
instance_flavor:
  - ins_name: uom.mse.1c4g
  - ins_name: uom.mse.2c9g
# Volumes
volumes:
  - vol_name: vol-nginx
    vol_size: 20
  - vol_name: vol-master
    vol_size: 60
  - vol_name: vol-slave0
    vol_size: 60
  - vol_name: vol-slave1
    vol_size: 60

# Security group
security_groups:
  - name: ssh
    description: "SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

  - name: http
    description: "HTTP access"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

  - name: nginx
    description: "proxy access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: db
    description: "db access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

  - name: db erlang
    description: "erlang access"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0

  - name: db cluster2
    description: "cluster access"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: nginxNode
    volumes: ['vol-nginx']
    instance_flavor: uom.mse.1c4g
  - name: masterNode
    volumes: ['vol-master']
    instance_flavor: uom.mse.2c9g
  - name: slaveNode0
    volumes: ['vol-slave0']
    instance_flavor: uom.mse.2c9g
  - name: slaveNode1
    volumes: ['vol-slave1']
    instance_flavor: uom.mse.2c9g

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: Group25
instance_network: qh2-uom-internal
