---
- name: Add proxy to environments
  become: yes
  lineinfile:
    line: "http_proxy=\"{{ proxy_address }}\"\nhttps_proxy=\"{{ proxy_address }}\"\nftp_proxy=\"{{ proxy_address }}\"\nno_proxy=\"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au\"\n"
    dest: /etc/environment

- name: make proxy available for current session
  become: yes
  shell: echo 'add proxy configuration success'
  environment:
    http_proxy: "{{ proxy_address }}"
    https_proxy: "{{ proxy_address }}"
    ftp_proxy: "{{ proxy_address }}"
    no_proxy: "localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"

- name: Unistall old versions of docker
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent
    update_cache: yes

- name: Install dependencies
  become: yes
  apt:
    name: ['apt-transport-https', 'vim', 'python3-apt', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    update_cache: no
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.25.5
    state: present

- name: Copy docker configuration file
  become: yes
  template:
    src: docker.service
    dest: /lib/systemd/system/docker.service
  
- name: stop docker
  become: yes
  raw: systemctl stop docker

- name: daemon-reload docker
  become: yes
  raw: systemctl daemon-reload

- name: enable docker
  become: yes
  raw: systemctl enable docker

- name: start docker
  become: yes
  raw: systemctl start docker